### ISSUE TITLE
crash on server

### ISSUE THREAD

**Issue by TheNimbleNinja** [shoaib11120/Accessibility-Plus-Extended#1]
https://gist.github.com/TheNimbleNinja/895537ece74f8e545915de261d38bce7

**Comment by shoaib11120** [comment]
@TheNimbleNinja Were you installing/using it in the server?? Cause this mod is client side only.

**Comment by TheNimbleNinja** [comment]
okay thanks for the info
i didnt know that

**Comment by shoaib11120** [comment]
no problem :)
